Repository MattW-source/discord-wilfred, pull requests merged in 2020-08, with the labels that each got.

#15 Kitten patch
  README.md
  commands/kitten.py
Labels: P3, enhancement

#22 Somewhat standardized shop messages
  commands/shop.py
Labels: P2

#96 Added ability to open multiple crates
  commands/crates.py
Labels: P3

#32 Merge 352 to 360
  commands/badge.py
  commands/balance.py
  commands/baltop.py
  commands/coinflip.py
  commands/cookie.py
  commands/cosmetics.py
  commands/crates.py
  commands/daily.py
  commands/economy.py
  commands/fight.py
  commands/help.py
  commands/hug.py
  commands/kitten.py
  commands/leaderboard.py
  commands/may.py
  commands/multiplier.py
  commands/ping.py
  commands/playing.py
  commands/poll.py
  commands/profile.py
  commands/puppy.py
  commands/raffle.py
  commands/ransack.py
  commands/shop.py
  commands/streaks.py
  commands/tag.py
  commands/weekly.py
  commands/xp.py
  events/command.py
  main.py
  utils/helpers.py
Labels: Task

#9 Merge Wilfred v3.5.2 to Master
  commands/badge.py
  commands/balance.py
  commands/baltop.py
  commands/coinflip.py
  commands/cookie.py
  commands/cosmetics.py
  commands/crates.py
  commands/daily.py
  commands/economy.py
  commands/fight.py
  commands/help.py
  commands/hug.py
  commands/kitten.py
  commands/leaderboard.py
  commands/may.py
  commands/multiplier.py
  commands/ping.py
  commands/playing.py
  commands/poll.py
  commands/profile.py
  commands/puppy.py
  commands/raffle.py
  commands/ransack.py
  commands/shop.py
  commands/streaks.py
  commands/tag.py
  commands/weekly.py
  commands/xp.py
  events/command.py
  main.py
  utils/helpers.py
Labels: Release

#293 Create pay command
  commands/help.py
  commands/pay.py
Labels: enhancement

#294 Fix cosmetics create command
  commands/cosmetics.py
Labels: bug

#282 Merge 360 to master
  Dockerfile
  commands/badge.py
  commands/baltop.py
  commands/cookie.py
  commands/cosmetics.py
  commands/crates.py
  commands/daily.py
  commands/help.py
  commands/leaderboard.py
  commands/pay.py
  commands/profile.py
  commands/shop.py
  commands/streaks.py
  commands/tag.py
  commands/weekly.py
  events/message.py
  requirements.txt
  special/advent.py
  special/daily-easter.py
  utils/database.py
  utils/helpers.py
  utils/values-redacted.py
Labels: Task
